# Generated by Django 5.1.6 on 2025-12-08 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_siembra', models.DateField()),
                ('fecha_estimada_cosecha', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('cantidad_plantas', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cultivos/')),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.area')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.producto')),
            ],
        ),
    ]
