# Generated by Django 5.1.6 on 2025-12-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Cultivo')),
                ('tipo', models.CharField(choices=[('CEREAL', 'Cereal'), ('HORTALIZA', 'Hortaliza'), ('FRUTA', 'Fruta'), ('LEGUMBRE', 'Legumbre'), ('TUBERCULO', 'Tubérculo'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_siembra', models.DateField(blank=True, null=True, verbose_name='Fecha de Siembra')),
                ('fecha_cosecha_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha Estimada de Cosecha')),
                ('area_sembrada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área Sembrada (m²)')),
                ('estado', models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('SEMBRADO', 'Sembrado'), ('CRECIMIENTO', 'En Crecimiento'), ('MADURO', 'Maduro'), ('COSECHADO', 'Cosechado'), ('FINALIZADO', 'Finalizado')], default='PLANIFICADO', max_length=20)),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Cultivo',
                'verbose_name_plural': 'Cultivos',
                'ordering': ['-created_at'],
            },
        ),
    ]
