# Generated by Django 5.2.9 on 2025-12-15 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('STOCK_LOW', 'Stock bajo'), ('PERIODIC', 'Periódico'), ('CUSTOM', 'Personalizado')], max_length=20)),
                ('target_type', models.CharField(max_length=30)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('mensaje_template', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('referencia', models.CharField(blank=True, max_length=255)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='alertas.alertrule')),
            ],
        ),
    ]
