# Generated by Django 5.2.9 on 2025-12-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='tipo',
            field=models.CharField(choices=[('STOCK_LOW', 'Stock bajo'), ('PERIODIC', 'Periódico'), ('CUSTOM', 'Personalizado / IA')], max_length=20),
        ),
    ]
