# Generated by Django 5.2.2 on 2025-12-11 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad_por_defecto', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='insumos/')),
            ],
            options={
                'db_table': 'insumo',
                'indexes': [models.Index(fields=['stock'], name='insumo_stock_775ced_idx')],
            },
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_planificada', models.DateField()),
                ('fecha_ejecutada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
            ],
            options={
                'db_table': 'consumo',
            },
        ),
        migrations.CreateModel(
            name='Consumo_insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.consumo')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.insumo')),
            ],
            options={
                'db_table': 'consumo_insumo',
                'unique_together': {('consumo', 'insumo')},
            },
        ),
        migrations.CreateModel(
            name='TasaConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_por_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_por_planta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.insumo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
            ],
            options={
                'db_table': 'tasa_consumo',
                'unique_together': {('producto', 'insumo')},
            },
        ),
    ]
