# Generated by Django 5.2.9 on 2025-12-19 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('TRACTOR', 'Tractor'), ('COSECHADORA', 'Cosechadora'), ('PULVERIZADORA', 'Pulverizadora'), ('OTRO', 'Otro')], max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('ficha_tecnica', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('OPERATIVA', 'Operativa'), ('MANTENIMIENTO', 'En mantenimiento'), ('FUERA_SERVICIO', 'Fuera de servicio')], default='OPERATIVA', max_length=50)),
                ('horas_uso', models.PositiveIntegerField(default=0)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('ultima_revision', models.DateField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='maquinaria/')),
                ('responsable_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquinarias', to='personal.personal')),
            ],
        ),
    ]
