# Generated by Django 5.2.9 on 2025-12-19 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultivos', '0001_initial'),
        ('maquinaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaAutomatizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('condicion', models.TextField()),
                ('accion', models.TextField()),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrediccionCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humedad', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('ph_suelo', models.FloatField()),
                ('riesgo', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], max_length=10)),
                ('resultado', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='cultivos.cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='PrediccionMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_desgaste', models.FloatField()),
                ('horas_uso', models.IntegerField()),
                ('vibracion', models.FloatField()),
                ('temperatura_motor', models.FloatField()),
                ('probabilidad_fallo', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='maquinaria.maquinaria')),
            ],
        ),
        migrations.CreateModel(
            name='EjecucionAutomatizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ia.reglaautomatizacion')),
            ],
        ),
    ]
