"""
Django settings for agro_bio project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv # uando python-dotenv para cargar variables de entorno desde un archivo .env
import os # Módulo os para acceder a las variables de entorno
from datetime import timedelta # Módulo datetime para manejar duraciones de tiempo


load_dotenv() # Cargar las variables de entorno desde el archivo .env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = "/media/"  # URL para acceder a los archivos multimedia
MEDIA_ROOT = BASE_DIR / "media" # Directorio donde se almacenan los archivos multimedia

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY") # Clave secreta para la aplicación Django desde las variables de entorno
DEBUG = os.getenv("DEBUG") == "True" # Modo de depuración desde las variables de entorno
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS").split(",") # Hosts permitidos desde las variables de entorno



# Definición de la configuración de Django REST Framework y Simple JWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}


AUTH_USER_MODEL = "usuarios.Usuario" # Modelo de usuario personalizado


# Configuración de Simple JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv("JWT_ACCESS_MINUTES", 60))), # Tiempo de vida del token de acceso en este caso 60 minutos
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv("JWT_REFRESH_DAYS", 1))), # Tiempo de vida del token de refresco en este caso 1 día
    'AUTH_HEADER_TYPES': ('Bearer',), # Tipo de encabezado de autorización
}






# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework', # Django REST Framework
    'alertas', # App de alertas
    'catalogo', # App de catálogo
    'cultivos', # App de cultivos
    'ia', # App de inteligencia artificial
    'maquinaria', # App de maquinaria
    'operaciones', # App de operaciones
    'personal', # App de personal
    'reportes', # App de reportes
    'usuarios', # App de usuarios
]

AUTH_USER_MODEL = "usuarios.Usuario"


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'agro_bio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'agro_bio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases




# Configuración de la base de datos utilizando variables de entorno
DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE"), # Motor de base de datos desde las variables de entorno
        "NAME": os.getenv("DB_NAME"), # Nombre de la base de datos desde las variables de entorno
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
