# Generated by Django 5.2.9 on 2025-12-19 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('cultivos', '0001_initial'),
        ('maquinaria', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_planificada', models.DateTimeField()),
                ('fecha_ejecutada', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('P', 'Planificado'), ('E', 'Ejecutado'), ('C', 'Cancelado')], default='P', max_length=1)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='cultivos.cultivo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='catalogo.producto')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos', to='personal.personal')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_detalle', to='operaciones.consumo')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumo_detalle', to='catalogo.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='Monitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(choices=[('FUM', 'Fumigación'), ('RIE', 'Riego'), ('ABO', 'Abonado'), ('POD', 'Poda'), ('OTR', 'Otro')], max_length=3)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_hora', models.DateTimeField()),
                ('evidencia', models.ImageField(blank=True, null=True, upload_to='monitoreo/evidencias/')),
                ('consumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoreos', to='operaciones.consumo')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoreos', to='cultivos.cultivo')),
                ('maquinaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usos', to='maquinaria.maquinaria')),
                ('personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoreos', to='personal.personal')),
            ],
        ),
    ]
